spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sanbosillok
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # only dev
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expire-length: ${ACCESS_TOKEN_EXPIRED_TIME}