spring:
  datasource:
    url: jdbc:mysql://sanbosillok-db.cj4kgvtjsgwk.ap-northeast-2.rds.amazonaws.com:3306/sanbosillok?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: tksqhtlffhr0!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expire-length: ${ACCESS_TOKEN_EXPIRED_TIME}
