name : sanbosillokServer

on:
  push:
    branches:
      - dev

jobs:
  CD:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: permission
        run: chmod +wrx gradlew

      - name: build
        run: gradlew build

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: sanbosillokServer
          path: build/libs/sanbosillokServer-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: sanbosillokServer
        path: build/libs/

    - name: Deploy to EC2
      run: |
        apt-get install sshpass
        sshpass -p ${{ secrets.EC2_PASSWORD }} scp build/libs/sanbosillokServer-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/sanbosillokServer.jar
        sshpass -p ${{ secrets.EC2_PASSWORD }} ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "pgrep java | xargs kill -9; nohup java -jar sanbosillokServer-0.0.1-SNAPSHOT.jar &"